---

- name: Cisco show commands example
  hosts: "{{ network_device }}"
  gather_facts: false

  tasks:
    - name: run show commands on the router
      ios_command:
        commands:
          - show version
          - show clock
          - show proc cpu | ex 0.00
          - show ip int br
      register: output

    - name: print output
      debug:
        var: output.stdout_lines


