---

- name: Cisco show version example
  hosts: sparks04
  gather_facts: false

  tasks:
    - name: run show version on the routers
      ios_command:
        commands: show version
      register: output

    - name: print output
      debug:
        var: output.stdout_lines


- name: Cisco show clock
  hosts: sparks04
  gather_facts: false

  tasks:
    - name: run show clock
      ios_command:
        commands: show clock
      register: output1

    - name: print output1
      debug:
        var: output1.stdout_lines


- name: Cisco show proc cpu
  hosts: sparks04
  gather_facts: false

  tasks:
    - name: run show proc cpu
      ios_command:
        commands: show proc cpu | ex 0.00
      register: output2

    - name: print output2
      debug:
        var: output2.stdout_lines

