---

- name: show junos example
  hosts: "{{ network_device }}"
  gather_facts: false
  ignore_errors: True

  tasks:
    - name: show junos example
      junos_command:
        commands:
        - "show version"
      register: output

    - name: print result
      debug:
        var: output.stdout_lines

    - name: collect junos facts
      junipernetworks.junos.junos_facts:
      register: output1
      
    - name: print model and version
      debug:
        msg: "Model: {{ output1.ansible_facts.ansible_net_model }} , Junos: {{ output1.ansible_facts.ansible_net_version }}"
        
