---
- name: show commands on Cisco IOS-XE
  hosts: "{{ network_device }}"
  ignore_errors: true
  gather_facts: false

  tasks:
    - name: show version
      ios_command:
        commands:
        - show version
      register: output

    - name: parse show version with parse_cli_textfsm
      ansible.builtin.set_fact:
        device_version_info: "{{ output.stdout[0] | parse_cli_textfsm('cisco_ios_show_version.textfsm') }}"

    - name: print show version with parse_cli_textfsm
      ansible.builtin.debug:
        msg: "{{ device_version_info }}"

    - name: parse show version with parse_cli_textfsm
      ansible.builtin.set_fact:
        device_uptime: "{{ output.stdout[0] | parse_cli_textfsm('cisco_ios_show_version.textfsm') }}"

    - name: print uptime with parse_cli_textfsm
      ansible.builtin.debug:
        msg: "uptime = {{ device_version_info[0].UPTIME }}"

#     - name: collect uptime using ansible.utils.cli_parse
#       ansible.utils.cli_parse:
#         command: show version
#         parser:
#           name: ansible.utils.textfsm
#           template_path: cisco_ios_uptime.textfsm
#       register: uptime

#     - name: print uptime using ansible.utils.textfsm
#       debug:
#         msg: "{{ uptime.parsed }}"
