---

- name: show junos example
  hosts: "{{ network_device }}"
  gather_facts: false
  ignore_errors: True

  tasks:
    - name: show junos example
      junos_command:
        commands:
        - "show version"
      register: output

    - name: print result
      debug:
        var: output.stdout_lines
